### ISSUE TITLE
docs request: guide on how to bind services to the server's node interface

### ISSUE THREAD

**Issue by OEvgeny** [gravitl/netmaker#622] opened 2022-01-18 19:56 UTC
I was able to successfully provision Netmaker server and client nodes, huge thanks for Netmaker and the great docs. 

For the server setup a default docker-compose was used, so the `nm-default` interface is listed only in the `netmaker` docker container and not exposed to the docker host.

My question is: how do I bind services directly to the `nm-default` interface created by netmaker, so they're only available through the netmaker VPN. Was trying to make tor to listen only on `10.xxx.xxx.xxx`. Speaking either of docker services/containers or docker host processes, and I don't see any way through.

**Comment by afeiszli** [comment] 2022-01-18 20:44
In general, the VPN agents for the server are meant to stay "contained" in docker. You can't really use them from the host. This is by design. To use a VPN interface on the host, for now you have to deploy an additional netclient like you would on any other server, but directly onto the host (outside of docker).

**Comment by afeiszli** [comment] 2022-03-25 15:27
Added in v0.10.0, closing

**Closed by afeiszli** 2022-03-25 15:27 UTC
Labels: documentation
