### ISSUE TITLE
Windows Client Scenario

### ISSUE THREAD

**Issue by doodlemania2** [gravitl/netmaker#1114] opened 2022-05-23 09:59 UTC
Attempted to use external client but couldn't make that work, so, I joined my laptop like a regular node with Windows. As a mobile device, would be great for it to auto-detect new local IP address more quickly. Took a number of steps repeatedly to force it to recognize the new IP address as I move around networks.

**Comment by afeiszli** [comment] 2022-05-23 11:38
Just to confirm, the issue is with getting a new Local IP address, not a new Public IP address?

I'm looking at the code and see an oversight in how we grab the local address on checkin, which is likely causing the issue.

**Comment by doodlemania2** [comment] 2022-05-23 14:30
Well, I've observed both actually @afeiszli  - I fixed the local one by updating manually in dashboard, but the public IP address only picks up if I disable/reenable the windows based connection which was strange.

**Comment by afeiszli** [comment] 2022-05-23 16:20
hmmm it sounds like maybe the daemon just isn't running locally?

**Comment by doodlemania2** [comment] 2022-05-23 17:46
When I start netmaker in Windows (Win11), it spawns a CMD window, then a GUI window. It doesn't like getting an update from my wifi on updated local or isp address without a number of contortions to the interface directly. Happy to debug with you if you like at some point.

**Comment by afeiszli** [comment] 2022-05-23 19:00
Did you install via MSI or just run the exe directly?

**Comment by doodlemania2** [comment] 2022-05-23 19:37
MSI based!

**Comment by afeiszli** [comment] 2022-05-23 23:44
Ahhh ok, the CMD window is not meant to be the one receiving the updates. There is a daemon running as a Windows Service that should be getting the updates. That said, there could be other issues blocking the process.

**Comment by doodlemania2** [comment] 2022-05-24 08:22
Found the services and started it (it was marked to start automatically but wasn't running). Once it started, it did in fact pull local updates and was reflected in the GUI a short time later. Mesh came up!

Still getting a warning from the GUI though, despite being connected on the "Last Check In" showing many days ago with a WARNING! message next to it.

Would be amazing if the GUI could show the individual peers connected status.

**Comment by afeiszli** [comment] 2022-05-24 12:02
hmmm ok, weird that it stopped...maybe after a restart? We should add a method to auto-update and track status of daemon via GUI, but it would be good to track down what caused the daemon to stop in the first place.

The WARNING in the gui is a bug that we've fixed for 0.14.1.

Other than that, is the client now recieving updates?

**Comment by doodlemania2** [comment] 2022-05-24 13:31
Ah! Perfect, yep - when I start that service, things happen pretty quick. Excited to try 0.14.1 shortly.

**Comment by afeiszli** [comment] 2022-05-25 14:31
@doodlemania2 just to confirm, does 0.14.1 fix your issues relating to: 
- Windows Service not running
- GUI displaying incorrect message

**Comment by doodlemania2** [comment] 2022-06-01 16:15
Updated all my linux machines like a champ but the windows update did not go smoothly - I uninstalled the 0.14.0 from control panel and then installed 0.14.1 via MSI. It errored indicating the following:
2022-06-01 11:13:04,360 INFO  - Installing service 'Netclient (netclient)'...
2022-06-01 11:13:04,367 ERROR - A service with ID 'netclient' already exists.
2022-06-01 11:13:04,370 FATAL - Failed to install the service. The specified service already exists.

[process exited with code 1073 (0x00000431)]

Likely the uninstallation didn't remove the service. I think I'm now stuck.

**Comment by afeiszli** [comment] 2022-06-01 17:10
hmmmm, are you able to manually remove the Windows Service?

**Comment by doodlemania2** [comment] 2022-06-01 17:13
Yes, sc delete for the win. However, reinstallation isn't detecting my wireguard installation (it's definitely installed) so am stuck at the moment on that node ... (test node so no urgency of course) happy to debug more just point me in the right direction!

**Comment by abhishek9686** [comment] 2024-06-02 13:00
@doodlemania2 can you try it out with the latest netmaker version?
I am closing this issue, feel free to open a new one, if you encounter new issues

**Closed by abhishek9686** 2024-06-02 13:00 UTC
