### ISSUE TITLE
[Bug]: iptables from docker

### ISSUE THREAD

**Issue by ahmaddxb** [gravitl/netmaker#917] opened 2022-03-18 13:05 UTC
### What happened?

I have setup Egress and iptables from docker client do not reflect on the host. Therefore i can not ping the clients internal network. If i manually enter the iptables rules on the host it works correctly.

### Version

v0.12.0

### What OS are you using?

Linux

### Contributing guidelines

- [X] Yes, I did.

**Comment by ahmaddxb** [comment] 2022-03-18 20:56
These command set fixed my issue

update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

**Comment by afeiszli** [comment] 2022-03-25 12:32
@ahmaddxb it sounds like the issue here is the version of iptables on the host machine, and that the issue is fixed?

If so, please close this issue. We can add this as a reference in the docs if others have the same issue: https://github.com/gravitl/netmaker-docs

**Closed** 2022-03-25 12:40 UTC
Labels: bug
