### ISSUE TITLE
node modification from netmaker server has problem

### ISSUE THREAD

**Issue by xindo451** [gravitl/netmaker#598] opened 2022-01-11 09:58 UTC
When node configuration is modified from netmaker server, windows wireguard client has problem to update local file, log consistently prints "[MGR] Unable to ingest and encrypt `C:\Program Files\WireGuard\Data\Configurations\nm-mynet.conf`: Cannot create a file when that file already exists.
"

**Comment by afeiszli** [comment] 2022-01-18 16:21
Duplicate of #559. Closing and will track via #559

**Closed by afeiszli** 2022-01-18 16:21 UTC
Labels: bug, agent, windows
