### ISSUE TITLE
[Bug]:  Add possibility to set domain name instead of public ip

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [gravitl/netmaker#1290] opened 2022-07-05 18:36 UTC
### Contact Details

friedemannblume@gmail.com

### What happened?

Could you add the option to edit the domain name of a node?

In an age of changing (Public)IPs it would add more redundancy from the netmaker-api / broker server if the wireguard vpn mesh uses domain names.

### Version

v0.14.4

### Relevant log output

```shell
.
```

### Contributing guidelines

- [X] Yes, I did.

**Comment by mattkasun** [comment] 2022-07-08 14:55
where exactly do you want to set the node's domain name?  there is no ui element for domain name of node

**Comment by crustulumtheoneandonly** [comment] 2022-07-08 17:08
Maybe the field „Endpoint“?

Mit freundlichen Grüßen
Friedemann Blume

**Comment by mattkasun** [comment] 2022-07-08 17:12
To what end?  This field is automatically updated by netclient whenever the public IP of a node changes.  The netmaker sever then distributes the update to all peers.

**Comment by crustulumtheoneandonly** [comment] 2022-07-08 19:04
I only know from simple Wireguard setups that it’s better to use a automatic updated dns record. (I’m talking about servers with dynamic IPs) In case of netmaker, this “update functionality” is covered by the netmaker-api.

The problem for high availability is, that if you don’t have netmaker server running in a seperate HA Cluster and netmaker server goes offline, the endpoint ip update is not longer possible. So it would make a lot of sense to add the possibility for a “static endpoint dns-record / domain” to keep the network alive in case the netmaker server goes offline and a node_public-ip changes.

You know what I mean?

Mit freundlichen Grüßen
Friedemann Blume

**Comment by mattkasun** [comment] 2022-07-08 20:01
Wireguard only resolves a DNS name when it first brings up the interface; after that it only uses IP addresses.   Wireguard updates the endpoint of peer whenever it receives a message (including persistent keepalive signals) from a peer.

**Comment by crustulumtheoneandonly** [comment] 2022-07-08 21:01
Oh ok
I Unterstand

Sorry I didn’t know the exact behaviour of peer updates in Wireguard.

So I guess it’s not possible to add this feature as a fallback setting for redundancy.

Sorry for bothering and thanks for your time.

You are making great work with netmaker, I really appreciate it👍👍

Mit freundlichen Grüßen
Friedemann Blume

**Comment by mattkasun** [comment] 2022-09-29 14:20
duplicate of #301

**Closed by mattkasun** 2022-09-29 14:20 UTC
Labels: duplicate, enhancement
